version: '3'

services:
  django:
    build: . 
    command: python manage.py runserver 0.0.0.0:8000
    depends_on: 
      - db
    ports:
       - "8000:8000"
    networks:
      - xedrum_network

  db:
    image: postgres:14.6-alpine
    restart: always
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
       - pg_data:/var/lib/postgresql
    networks:
      - xedrum_network

  nginx:
    image: nginx:1.25.0-alpine
    depends_on:
      - django
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/backend/staticfiles/
      - media_volume:/backend/mediafiles/
    networks:
      - xedrum_network

volumes:
  pg_data:
  static_volume:
  media_volume:

networks:
  xedrum_network:
    driver: bridge
